# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

executors:
  go-container:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/jeremiefourbil/nextjs0/api

jobs:
  build:
    executor:
      name: go-container
    steps:
      - checkout
      - run: cd api && go install github.com/jeremiefourbil/nextjs0/api
  lint:
    docker:
      - image: golangci/golangci-lint:v1.37-alpine
    steps:
      - checkout
      - run: cd api && golangci-lint run
  test:
    executor:
      name: go-container
    steps:
      - checkout
      - run: cd api && go test -v ./...

workflows:
  build_lint_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires: 
            - lint